CREATE TABLE IF NOT EXISTS public.users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role_id INTEGER REFERENCES roles (id) ON DELETE CASCADE NOT NULL DEFAULT 1,
    status_id INTEGER REFERENCES account_status (id) ON DELETE CASCADE NOT NULL DEFAULT 1
);
